In [42]:
import pandas as pd
import numpy as np
import yfinance as yf

In [43]:
df = pd.read_csv("stock_data_daily.csv")
df.Date = pd.to_datetime(df.Date)
df = df.set_index('Date')

In [44]:
df.tail()

,Open_XU100,High_XU100,Low_XU100,Close_XU100,Adj Close_XU100,Volume_XU100,Open_AEFES.IS,High_AEFES.IS,Low_AEFES.IS,Close_AEFES.IS,...,Adj Close_YYLGD.IS,Volume_YYLGD.IS,score_YYLGD.IS,Open_ZOREN.IS,High_ZOREN.IS,Low_ZOREN.IS,Close_ZOREN.IS,Adj Close_ZOREN.IS,Volume_ZOREN.IS,score_ZOREN.IS
Date,,,,,,,,,,,,,,,,,,,,,
2024-05-15,10171.099609,10241.000000,10121.700195,10158.599609,10158.599609,2379755600,197.000000,199.699997,192.600006,194.399994,...,13.05,9098754.0,50.0,5.92,5.98,5.81,5.85,5.85,143404679.0,50.0
2024-05-16,10189.099609,10320.000000,10145.099609,10320.000000,10320.000000,2964017900,194.399994,208.000000,194.399994,208.000000,...,13.17,5631192.0,50.0,5.88,6.12,5.85,6.07,6.07,353584533.0,50.0
2024-05-17,10369.900391,10652.299805,10357.000000,10643.599609,10643.599609,3252227500,208.000000,211.100006,206.000000,208.199997,...,13.19,7259318.0,50.0,6.09,6.20,6.07,6.09,6.09,179759508.0,50.0
2024-05-20,10660.799805,10775.000000,10633.900391,10739.599609,10739.599609,3307518800,208.600006,212.000000,205.500000,208.100006,...,13.50,15191617.0,50.0,6.10,6.34,6.09,6.31,6.31,230927389.0,50.0
2024-05-21,10767.339844,11088.009766,10751.980469,10943.190430,10943.190430,0,208.399994,212.399994,206.800003,209.000000,...,13.53,15567320.0,50.0,6.35,6.44,6.27,6.36,6.36,228724554.0,50.0

In [45]:
last_day = df.tail(1)
last_day_index = last_day.index

In [46]:
last_day

,Open_XU100,High_XU100,Low_XU100,Close_XU100,Adj Close_XU100,Volume_XU100,Open_AEFES.IS,High_AEFES.IS,Low_AEFES.IS,Close_AEFES.IS,...,Adj Close_YYLGD.IS,Volume_YYLGD.IS,score_YYLGD.IS,Open_ZOREN.IS,High_ZOREN.IS,Low_ZOREN.IS,Close_ZOREN.IS,Adj Close_ZOREN.IS,Volume_ZOREN.IS,score_ZOREN.IS
Date,,,,,,,,,,,,,,,,,,,,,
2024-05-21,10767.339844,11088.009766,10751.980469,10943.19043,10943.19043,0,208.399994,212.399994,206.800003,209.0,...,13.53,15567320.0,50.0,6.35,6.44,6.27,6.36,6.36,228724554.0,50.0

In [47]:
last_day_index

DatetimeIndex(['2024-05-21'], dtype='datetime64[ns]', name='Date', freq=None)

In [48]:
start_str = str(last_day_index[0]).split(' ')[0]

In [49]:
def add_stock (index, main_df):
    new_df = yf.download(index, start=start_str, interval="1d")
    stock_score = 'score'
    st_sc = stock_score + "_" + index
    new_df[stock_score] = float(df.loc[last_day_index, st_sc].iloc[0])
    new_df = new_df.add_suffix('_' + index)
    main_df = main_df.join(new_df,how='left')
    return main_df

In [50]:
new_val = yf.download('XU100.IS', start=start_str, interval="1d")
new_val = new_val.add_suffix('_' + 'XU100')
with open("bist_100.txt") as f:
    bist_list = f.read().splitlines()

for line in bist_list:
    index = line + ".IS"
    new_val = add_stock(index, new_val)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [52]:
df = df[:-1]

In [53]:
result = pd.concat([df, new_val], axis=0)
result

,Open_XU100,High_XU100,Low_XU100,Close_XU100,Adj Close_XU100,Volume_XU100,Open_AEFES.IS,High_AEFES.IS,Low_AEFES.IS,Close_AEFES.IS,...,Adj Close_YYLGD.IS,Volume_YYLGD.IS,score_YYLGD.IS,Open_ZOREN.IS,High_ZOREN.IS,Low_ZOREN.IS,Close_ZOREN.IS,Adj Close_ZOREN.IS,Volume_ZOREN.IS,score_ZOREN.IS
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-02,7542.299805,7634.100098,7542.299805,7624.299805,7624.299805,2397081700,137.000000,140.000000,135.199997,138.000000,...,12.88,12438597.0,50.0,4.26,4.41,4.22,4.37,4.37,111809201.0,50.0
2024-01-03,7624.600098,7624.600098,7411.799805,7412.000000,7412.000000,2169646100,138.000000,138.199997,131.899994,131.899994,...,12.18,11671190.0,50.0,4.36,4.37,4.17,4.17,4.17,104408356.0,50.0
2024-01-04,7421.899902,7547.799805,7387.000000,7547.799805,7547.799805,2391591200,132.100006,132.800003,128.100006,131.300003,...,12.43,12559812.0,50.0,4.16,4.27,4.16,4.25,4.25,60182709.0,50.0
2024-01-05,7570.100098,7628.700195,7532.200195,7628.700195,7628.700195,2355101900,131.699997,132.899994,128.899994,131.399994,...,12.74,9836294.0,50.0,4.29,4.67,4.29,4.48,4.48,289683881.0,50.0
2024-01-08,7667.899902,7824.600098,7667.899902,7818.899902,7818.899902,2873781100,132.000000,133.000000,130.000000,130.300003,...,12.75,13399708.0,50.0,4.50,4.59,4.49,4.51,4.51,96531756.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-05-17,10369.900391,10652.299805,10357.000000,10643.599609,10643.599609,3252227500,208.000000,211.100006,206.000000,208.199997,...,13.19,7259318.0,50.0,6.09,6.20,6.07,6.09,6.09,179759508.0,50.0
2024-05-20,10660.799805,10775.000000,10633.900391,10739.599609,10739.599609,3307518800,208.600006,212.000000,205.500000,208.100006,...,13.50,15191617.0,50.0,6.10,6.34,6.09,6.31,6.31,230927389.0,50.0
2024-05-21,10767.299805,11088.000000,10752.000000,10895.299805,10895.299805,5625623300,208.399994,212.399994,204.300003,204.300003,...,13.45,18320222.0,50.0,6.35,6.44,6.27,6.35,6.35,287982706.0,50.0
2024-05-22,10930.400391,11024.500000,10800.900391,10899.299805,10899.299805,3429268100,205.000000,209.699997,204.100006,204.399994,...,13.85,13588857.0,50.0,6.38,6.44,6.22,6.33,6.33,274333691.0,50.0
2024-05-23,10869.549805,10972.730469,10820.200195,10839.040039,10839.040039,0,203.800003,206.199997,202.199997,204.399994,...,14.07,16767373.0,50.0,6.31,6.31,6.02,6.06,6.06,205873398.0,50.0

In [56]:
result.to_csv('stock_data_daily.csv')